args <- commandArgs()

help <- function(){
    cat("PROseq_makeMetaPlot.R :
- Make meta plots for sense and anti sense strand tables generated by PROseq_heatMatrix.R and save as pdf\n")
    cat("Usage: \n")
    cat("--Dir        : path to heatmap tables                                          [required]\n")
    cat("--Pattern    : grep pattern for heatmap tables to use quotes (ex. PolII.*293T) [optional]\n")    
    cat("--outName    : prefix for plot name. Type will be appended to this in script   [required]\n")
    cat("--cols       : tab delimited text file with headers sample and color           [default = rainbow]\n")
    cat("--bins       : number of bins each window is (ie 0, 25, or 50)                 [default = 25]\n")
    cat("--Type       : Tss, Tes, Peaks                                                 [default = Tss]\n")
    cat("--Height     : plot height will be set the same for plus and minus             [default = max of sense and min of anti]\n")
    cat("--upStream   : number of bp upstream of Tss in matrix                          [required]\n")
    cat("--downStream : number of bp downstream of Tss in matrix                        [required]\n")
    cat("\n")
    q()
}

## Save values of each argument
if(length(args)==0 || !is.na(charmatch("-help",args))){
    help()
} else {
    Dir  <- sub( '--Dir=', '', args[grep('--Dir=', args)])
    Pattern    <- sub( '--Pattern=', '', args[grep('--Pattern=', args)])
    outName    <- sub( '--outName=', '',args[grep('--outName=',args)])
    cols       <- sub( '--cols=', '',args[grep('--cols=',args)])
    bins       <- sub( '--bins=', '',args[grep('--bins=',args)])
    Type       <- sub( '--Type=', '',args[grep('--Type=',args)])
    Height     <- sub( '--Height=', '',args[grep('--Height=',args)])
    upStream   <- as.numeric( sub( '--upStream=', '',args[grep('--upStream=',args)]) )
    downStream <- as.numeric( sub( '--downStream=', '',args[grep('--downStream=',args)]) )
}

## for testing
#setwd("/projects/b1025/arw/analysis/yuki/degrons/DLD1/")
#Pattern <- "PRO.*NELFcAID_DLD_1057_Tssup50down100bins0"
#Dir     <- "tables/heatmaps"
#outName <- "test"
#cols <- "tables/plotCols/PRO_1057_colors.txt"
#Type <- "Tss"
#bins <- 0
#upStream <- 50
#downStream <- 100

library(RColorBrewer)
library(viridis)
library(reshape2)
library(ggplot2)

## set defaults
if (identical(bins,character(0))){
   bins <- 25
}else{
    bins <- as.numeric(bins)
}

if (identical(Type,character(0))){
   Type <- "Tss"
}

Dir
foo <- list.files(Dir, pattern=".rda", full.names=TRUE)
foo <- foo[grep(Pattern,foo,invert=FALSE)]
foo <- foo[grep(Type,foo,invert=FALSE)]
foo

## load files and assign to file name
for (i in 1:length(foo))
{
    oname = sub( "rda", "df", gsub("_Tss.*[0-9]|_Tes.*[0-9]|_Peak.*[0-9]","",basename(foo[i])) )
    oname <- gsub("-","_",oname)
    df <- get(load(foo[i]))
    print(oname)
    assign(oname, df)
}

SAMPLES <- ls(pattern=".df$")
SAMPLES <- SAMPLES[grep("^anti.df$|^sense.df$", SAMPLES, invert=TRUE)]
SAMPLES

## make a data frame with matrix column averages
df <- do.call(cbind, lapply(SAMPLES, function(x){
    if( length(grep("anti", x)) ==1) {
        avg           <- as.data.frame( -1*colMeans(get(x) ))
    }else{
        avg           <- as.data.frame( colMeans(get(x) ))
    }
    colnames(avg) <- sub(".df", "", x)
    avg
  }
))
df$x <- seq(1,nrow(df))
df.long <- melt(df, id.vars = "x")


mround <- function(x,base){ 
    base*ceiling(x/base) 
} 

if( max(df[,grep("^x$",names(df),invert=TRUE)]) > 0.5 ){
    Ymax <- mround(ceiling(max(df[,grep("^x$|anti$",names(df),invert=TRUE)])),1)
    Min  <- mround(min(df[,grep("^x$|sense$",names(df),invert=TRUE)]),-0.05)
}else{
    Ymax <- mround(max(df[,grep("^x$|anti$",names(df),invert=TRUE)]),0.05)
    Min  <- mround(min(df[,grep("^x$|sense$",names(df),invert=TRUE)]),-0.05)
}

if (identical(Height, character(0))){
    Height <- Ymax
}else{
    Height <- as.numeric(Height)
    Min <- as.numeric(Height)
}

## if we want to plot lower values first must factor and reorder the colors
#df.long$variable <- factor(df.long$variable, levels=names(hmm[ order(hmm, decreasing=TRUE) ])
#hmm <- apply(df[,1:14], 2, max)
#Cols             <- paste(df.col[sub(".sense|.anti", "", names(hmm[ order(hmm, decreasing=TRUE) ])), "color"])


if (identical(cols,character(0))){
    Cols <- rainbow(length(foo))#viridis(length(foo))
}else{
    df.col           <- read.table(cols,sep="\t", header=TRUE, comment.char = "")
    rownames(df.col) <- paste(df.col$sample)
                                        #Cols             <- paste(df.col[sub(".df", "", SAMPLES), "color"])
    Cols             <- paste(df.col[sub(".anti.df|.sense.df", "", SAMPLES), "color"])
}

if(!(file.exists( dirname(outName) ))) {
    print(paste("mkdir", dirname(outName)))
    dir.create(dirname(outName),FALSE,TRUE)  
}

Labels <- c(paste0("-",upStream)
           ,Type
           ,paste0("+", downStream))


if(bins==0){
    Breaks <- c(0
               ,upStream
               ,upStream + downStream)
}else{
    Breaks <- c(0
               ,upStream/bins
               ,(upStream + downStream)/bins)   
}

pdf(file=sub("$", paste0(Type, ".metaPlot.pdf"), outName),width=9,height=5)
print({
    p <-        
    ggplot(df.long, aes(x=x, y=value, color=variable)) +
    geom_hline(yintercept = 0) + 
    geom_line(size=1)+
    scale_color_manual("sample", values = Cols )+
        scale_x_continuous(breaks = Breaks
                          ,labels = Labels
                           )+
    ylab("r.p.m.")+
    xlab("")+
    ylim(Min,Height)+
    ggtitle(basename(outName))+
    theme(panel.grid.major = element_blank()
         ,panel.grid.minor = element_blank(), 
          panel.background = element_blank(),
          axis.line = element_line(colour = "black"),
          legend.key=element_blank())+
    theme(text = element_text(size=12),
          axis.text.x = element_text(vjust=1,color="black",size=12),
          axis.text.y = element_text(color="black",size=12),
          plot.title=element_text(size=12))
})
dev.off()

## check the colors are right and save incase we scrap ggplot later
## matplot(df$x, as.matrix(df[, grep("^x$", names(df), invert=TRUE)]), type = "l", lty = 1, lwd=3, col=Cols)
